universe:
  - SPY
  - AAPL
  - MSFT
  - KO
  - NVDA
  - TSLA
  - FIZZ
  - PLTR
  - COIN
  - BRK.B
  
  vendors:
  yfinance:
    period: max
    interval: 1d
    auto_adjust: false
    actions: true
    prepost: false
    repair: false

  alpha_vantage:
    function: TIME_SERIES_DAILY
    outputsize: compact
    datatype: csv
    
 symbol_overrides:
  BRK.B:
    yfinance: BRK-B
    alpha_vantage: BRK-B   
    
